"""pricelist

Revision ID: 016f54be53fe
Revises: c3b3a6b885e7
Create Date: 2025-09-25 12:32:40.907907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016f54be53fe'
down_revision: Union[str, Sequence[str], None] = 'c3b3a6b885e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_work', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('in_stock_quantity', sa.Float(), nullable=True),
    sa.Column('using', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricelist')
    # ### end Alembic commands ###
