"""hire_and_fire_dates

Revision ID: 67bd55cf42a6
Revises: 016f54be53fe
Create Date: 2025-10-03 09:23:25.189929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bd55cf42a6'
down_revision: Union[str, Sequence[str], None] = '016f54be53fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('profile', sa.Column('fire_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'fire_date')
    op.drop_column('profile', 'hire_date')
    # ### end Alembic commands ###
