"""responsibles

Revision ID: 6d437cb9e5ad
Revises: e2aa584c6b4d
Create Date: 2025-12-14 13:43:19.567737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d437cb9e5ad'
down_revision: Union[str, Sequence[str], None] = 'e2aa584c6b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('responsible_mechanic_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('responsible_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'profile', ['responsible_mechanic_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'profile', ['responsible_admin_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'responsible_admin_id')
    op.drop_column('orders', 'responsible_mechanic_id')
    # ### end Alembic commands ###
