"""wiki

Revision ID: 7c8a2c2863f3
Revises: 67bd55cf42a6
Create Date: 2025-10-03 12:06:14.402519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c8a2c2863f3'
down_revision: Union[str, Sequence[str], None] = '67bd55cf42a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brands', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('syndrome', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
